// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */
enum ElementEnum {
  Water,
  Earth,
  Fire,
  Air
}

enum GrowthLevelEnum {
  Seed,
  Sprout,
  Flowering,
  Mature
}

enum CellTypeEnum {
  Empty,
  Plant,
  Creature
}

enum GridTypeEnum {
  TicTacToe,
  Checkers,
  Ludo,
  Chess
}

enum MapTypeEnum {
  Private,
  Public
}

enum SizeEnum {
  Small,
  Medium,
  Large,
  Massive
}

enum TransferStatusEnum {
  Pending,
  Completed,
  Failed
}

enum AccountTypeEnum {
  Keeper,
  Space,
  Plant,
  Creature
}
