// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Water, WaterTableId } from "./tables/Water.sol";
import { Earth, EarthTableId } from "./tables/Earth.sol";
import { Fire, FireTableId } from "./tables/Fire.sol";
import { Air, AirTableId } from "./tables/Air.sol";
import { Element, ElementTableId } from "./tables/Element.sol";
import { Cell, CellData, CellTableId } from "./tables/Cell.sol";
import { Grid, GridData, GridTableId } from "./tables/Grid.sol";
import { Map, MapData, MapTableId } from "./tables/Map.sol";
import { Asset, AssetData, AssetTableId } from "./tables/Asset.sol";
import { Identity, IdentityData, IdentityTableId } from "./tables/Identity.sol";
import { Owner, OwnerTableId } from "./tables/Owner.sol";
import { Token, TokenData, TokenTableId } from "./tables/Token.sol";
import { Coordinate, CoordinateData, CoordinateTableId } from "./tables/Coordinate.sol";
import { Tag, TagData, TagTableId } from "./tables/Tag.sol";
import { Home, HomeTableId } from "./tables/Home.sol";
import { Members, MembersTableId } from "./tables/Members.sol";
import { Health, HealthData, HealthTableId } from "./tables/Health.sol";
import { Care, CareData, CareTableId } from "./tables/Care.sol";
import { Species, SpeciesData, SpeciesTableId } from "./tables/Species.sol";
import { Energy, EnergyTableId } from "./tables/Energy.sol";
import { Power, PowerTableId } from "./tables/Power.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
