// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { CellTypeEnum } from "./../common.sol";

/**
 * @title ICellSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICellSystem {
  function createCell(bytes32 gridId, int32 position, CellTypeEnum cellType, address entity) external;

  function setCell(bytes32 cellId, CellTypeEnum cellType, int32 position, address value) external;
}
