// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICellSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICellSystem {
  function setCell(bytes32 worldId, bytes32 spaceId, uint8 position, bytes32 value) external;
}
