// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICreatureSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICreatureSystem {
  function redeemCreature(
    string memory image,
    string memory meta,
    int32 longitude,
    int32 latitude,
    address spaceAddrs
  ) external;

  function nurtureCreature(bytes32 _entity, int32 _energy) external;

  function evolveCreature(bytes32 _entity, string memory _image, string memory _meta) external;
}
