// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGameStartSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameStartSystem {
  function createGame(string memory name, bytes32 worldId, bytes32 spaceId) external returns (bytes32);

  function joinGame(bytes32 gameId) external returns (bool);
}
