// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGameMoveSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameMoveSystem {
  function claimPosition(bytes32 gameId, uint8 matchNumber, uint8 x) external;
}
