// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGridSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGridSystem {
  function transferGrid(bytes32 worldId, bytes32 spaceId, address to) external returns (bytes32);

  function setGrid(
    bytes32 worldId,
    bytes32 spaceId,
    string memory name,
    string memory description,
    string memory image
  ) external returns (bytes32);
}
