// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { SizeEnum, GridTypeEnum } from "./../common.sol";

/**
 * @title IGridSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGridSystem {
  function claimGrid(bytes32 mapId, SizeEnum size) external returns (bytes32);

  function setGrid(bytes32 gridId, GridTypeEnum gridType) external;
}
