// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IKeeperSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IKeeperSystem {
  function createKeeper(
    string memory image,
    string memory meta,
    int32 longitude,
    int32 latitude,
    address spaceAddrs
  ) external;

  function destroyKeeper(bytes32 _entity, int32 _energy) external;
}
