// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { SizeEnum, MapTypeEnum } from "./../common.sol";

/**
 * @title IMapSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMapSystem {
  function createMap(
    bytes32 spaceId,
    string memory metadata,
    string memory image,
    SizeEnum size,
    MapTypeEnum mapType
  ) external returns (bytes32);

  function claimGrid(bytes32 mapId) external returns (bytes32);
}
