// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IPlantSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPlantSystem {
  function redeem(
    string memory image,
    string memory meta,
    int32 long,
    int32 lat,
    address userAddrs
  ) external returns (bytes32);
}
