// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";

import { ICellSystem } from "./ICellSystem.sol";
import { ICreatureSystem } from "./ICreatureSystem.sol";
import { IGameMoveSystem } from "./IGameMoveSystem.sol";
import { IGameStartSystem } from "./IGameStartSystem.sol";
import { IGridSystem } from "./IGridSystem.sol";
import { IIncrementSystem } from "./IIncrementSystem.sol";
import { IKeeperSystem } from "./IKeeperSystem.sol";
import { IMapSystem } from "./IMapSystem.sol";
import { ITokenSystem } from "./ITokenSystem.sol";

/**
 * @title IWorld
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  ICellSystem,
  ICreatureSystem,
  IGameMoveSystem,
  IGameStartSystem,
  IGridSystem,
  IIncrementSystem,
  IKeeperSystem,
  IMapSystem,
  ITokenSystem
{

}
